# map_character_anims.ps1
# Maps imported Mixamo animations from _anim_import/ to per-character anims/ folders.
# Each character gets a UNIQUE selection for distinct fighting styles.

$root = "D:\Games\finalfighter_-_characters_part_01"
$src = "$root\_anim_import"
$dst = "$root\anims"

function Copy-Anim($from, $toDir, $toName) {
    $srcPath = Join-Path $src $from
    if (-not (Test-Path $srcPath)) { Write-Warning "MISSING: $from"; return }
    $dstDir = Join-Path $dst $toDir
    if (-not (Test-Path $dstDir)) { New-Item -ItemType Directory -Path $dstDir -Force | Out-Null }
    $dstPath = Join-Path $dstDir "$toName.glb"
    Copy-Item $srcPath $dstPath -Force
    Write-Host "  $toDir/$toName.glb <- $from"
}

# ===== Cao Pi (Model001) — Swordsman: precise sword+shield style =====
Write-Host "`n--- CaoPi (sword+shield precise) ---"
Copy-Anim "sword_shield\sword and shield attack.glb"      "CaoPi" "attack_1"
Copy-Anim "sword_shield\sword and shield attack (2).glb"   "CaoPi" "attack_2"
Copy-Anim "sword_shield\sword and shield attack (3).glb"   "CaoPi" "attack_3"
Copy-Anim "sword_shield\sword and shield slash.glb"         "CaoPi" "attack_4"
Copy-Anim "sword_shield\sword and shield slash (2).glb"     "CaoPi" "attack_5"
Copy-Anim "sword_shield\sword and shield slash (3).glb"     "CaoPi" "attack_6"
Copy-Anim "sword_shield\sword and shield slash (4).glb"     "CaoPi" "attack_7"
Copy-Anim "sword_shield\sword and shield kick.glb"          "CaoPi" "attack_8"
Copy-Anim "sword_shield\sword and shield casting.glb"       "CaoPi" "attack_9"
Copy-Anim "sword_shield\sword and shield slash (5).glb"     "CaoPi" "attack_10"
Copy-Anim "sword_shield\sword and shield block.glb"         "CaoPi" "block"
Copy-Anim "sword_shield\sword and shield block (2).glb"     "CaoPi" "parry"
Copy-Anim "sword_shield\sword and shield impact.glb"        "CaoPi" "hit_react"
Copy-Anim "sword_shield\sword and shield impact (2).glb"    "CaoPi" "block_stun"
Copy-Anim "sword_shield\sword and shield idle.glb"          "CaoPi" "idle"
Copy-Anim "sword_shield\sword and shield run.glb"           "CaoPi" "run_fwd"
Copy-Anim "sword_shield\sword and shield walk.glb"          "CaoPi" "walk_fwd"
Copy-Anim "sword_shield\sword and shield crouch.glb"        "CaoPi" "crouch"
Copy-Anim "sword_shield\sword and shield jump.glb"          "CaoPi" "jump"
Copy-Anim "sword_shield\sword and shield death.glb"         "CaoPi" "ko"
Copy-Anim "sword_shield\sword and shield power up.glb"      "CaoPi" "taunt"
Copy-Anim "sword_shield\sword and shield casting (2).glb"   "CaoPi" "victory"
Copy-Anim "sword_shield\sheath sword 1.glb"                 "CaoPi" "intro"
Copy-Anim "sword_shield\sword and shield crouch block.glb"  "CaoPi" "dodge"

# ===== Cao Zijian (Model002) — Strategist: magic caster style =====
Write-Host "`n--- CaoZijian (magic caster) ---"
Copy-Anim "magic_caster\standing idle.glb"                       "CaoZijian" "idle"
Copy-Anim "magic_caster\Standing Walk Forward.glb"               "CaoZijian" "walk_fwd"
Copy-Anim "magic_caster\Standing Walk Back.glb"                  "CaoZijian" "walk_back"
Copy-Anim "magic_caster\Standing Run Forward.glb"                "CaoZijian" "run_fwd"
Copy-Anim "magic_caster\Standing Run Back.glb"                   "CaoZijian" "run_back"
Copy-Anim "magic_caster\Standing 1H Magic Attack 01.glb"         "CaoZijian" "attack_3"
Copy-Anim "magic_caster\Standing 2H Magic Area Attack 02.glb"    "CaoZijian" "attack_9"
Copy-Anim "magic_caster\Standing React Small From Front.glb"     "CaoZijian" "hit_react"
Copy-Anim "magic_caster\Standing React Large From Front.glb"     "CaoZijian" "knockdown"
Copy-Anim "magic_caster\Standing React Death Backward.glb"       "CaoZijian" "ko"
Copy-Anim "magic_caster\Standing Jump.glb"                       "CaoZijian" "jump"

# ===== Dian Wei (Model003) — Berserker: heavy great sword, aggressive =====
Write-Host "`n--- DianWei (great sword berserker) ---"
Copy-Anim "great_sword\great sword attack.glb"            "DianWei" "attack_1"
Copy-Anim "great_sword\great sword slash.glb"              "DianWei" "attack_2"
Copy-Anim "great_sword\great sword slash (2).glb"          "DianWei" "attack_3"
Copy-Anim "great_sword\great sword slash (3).glb"          "DianWei" "attack_4"
Copy-Anim "great_sword\great sword slash (4).glb"          "DianWei" "attack_5"
Copy-Anim "great_sword\great sword high spin attack.glb"   "DianWei" "attack_6"
Copy-Anim "great_sword\great sword slide attack.glb"       "DianWei" "attack_7"
Copy-Anim "great_sword\great sword kick.glb"               "DianWei" "attack_8"
Copy-Anim "great_sword\great sword casting.glb"            "DianWei" "attack_9"
Copy-Anim "great_sword\great sword jump attack.glb"        "DianWei" "attack_10"
Copy-Anim "great_sword\great sword blocking.glb"           "DianWei" "block"
Copy-Anim "great_sword\great sword blocking (2).glb"       "DianWei" "parry"
Copy-Anim "great_sword\great sword impact.glb"             "DianWei" "hit_react"
Copy-Anim "great_sword\great sword impact (2).glb"         "DianWei" "block_stun"
Copy-Anim "great_sword\great sword idle.glb"               "DianWei" "idle"
Copy-Anim "great_sword\great sword run.glb"                "DianWei" "run_fwd"
Copy-Anim "great_sword\great sword run (2).glb"            "DianWei" "run_back"
Copy-Anim "great_sword\great sword walk.glb"               "DianWei" "walk_fwd"
Copy-Anim "great_sword\great sword walk (2).glb"           "DianWei" "walk_back"
Copy-Anim "great_sword\great sword crouching.glb"          "DianWei" "crouch"
Copy-Anim "great_sword\great sword jump.glb"               "DianWei" "jump"
Copy-Anim "great_sword\two handed sword death.glb"         "DianWei" "ko"
Copy-Anim "great_sword\great sword power up.glb"           "DianWei" "taunt"
Copy-Anim "great_sword\draw a great sword 1.glb"           "DianWei" "intro"
Copy-Anim "great_sword\great sword strafe.glb"             "DianWei" "dodge"
Copy-Anim "great_sword\great sword impact (3).glb"         "DianWei" "knockdown"
Copy-Anim "great_sword\spell cast.glb"                     "DianWei" "victory"

# ===== Diao Chan (Model004) — Enchantress: magic + graceful sword style =====
Write-Host "`n--- DiaoChan (enchantress magic+grace) ---"
Copy-Anim "magic_caster\standing idle 02.glb"                    "DiaoChan" "idle"
Copy-Anim "magic_caster\Standing Walk Forward.glb"               "DiaoChan" "walk_fwd"
Copy-Anim "magic_caster\Standing Walk Back.glb"                  "DiaoChan" "walk_back"
Copy-Anim "magic_caster\Standing Run Forward.glb"                "DiaoChan" "run_fwd"
Copy-Anim "magic_caster\Standing Run Back.glb"                   "DiaoChan" "run_back"
Copy-Anim "magic_caster\Standing 1H Magic Attack 01.glb"         "DiaoChan" "attack_5"
Copy-Anim "magic_caster\Standing 2H Magic Area Attack 02.glb"    "DiaoChan" "attack_6"
Copy-Anim "magic_caster\Standing React Small From Front.glb"     "DiaoChan" "hit_react"
Copy-Anim "magic_caster\Standing React Large From Front.glb"     "DiaoChan" "knockdown"
Copy-Anim "magic_caster\Standing React Death Backward.glb"       "DiaoChan" "ko"
Copy-Anim "magic_caster\Standing Jump.glb"                       "DiaoChan" "jump"

# ===== Dong Zhuo (Model005) — Tyrant: brutal great sword, different subset =====
Write-Host "`n--- DongZhuo (great sword tyrant) ---"
Copy-Anim "great_sword\great sword slash (5).glb"          "DongZhuo" "attack_1"
Copy-Anim "great_sword\great sword attack.glb"             "DongZhuo" "attack_2"
Copy-Anim "great_sword\great sword slash (3).glb"          "DongZhuo" "attack_3"
Copy-Anim "great_sword\great sword slash (4).glb"          "DongZhuo" "attack_4"
Copy-Anim "great_sword\great sword kick (2).glb"           "DongZhuo" "attack_5"
Copy-Anim "great_sword\great sword high spin attack.glb"   "DongZhuo" "attack_6"
Copy-Anim "great_sword\great sword kick.glb"               "DongZhuo" "attack_7"
Copy-Anim "great_sword\great sword jump attack.glb"        "DongZhuo" "attack_8"
Copy-Anim "great_sword\great sword casting.glb"            "DongZhuo" "attack_9"
Copy-Anim "great_sword\great sword slide attack.glb"       "DongZhuo" "attack_10"
Copy-Anim "great_sword\great sword blocking (3).glb"       "DongZhuo" "block"
Copy-Anim "great_sword\great sword blocking.glb"           "DongZhuo" "parry"
Copy-Anim "great_sword\great sword impact (4).glb"         "DongZhuo" "hit_react"
Copy-Anim "great_sword\great sword impact (5).glb"         "DongZhuo" "block_stun"
Copy-Anim "great_sword\great sword idle (2).glb"           "DongZhuo" "idle"
Copy-Anim "great_sword\great sword run.glb"                "DongZhuo" "run_fwd"
Copy-Anim "great_sword\great sword walk.glb"               "DongZhuo" "walk_fwd"
Copy-Anim "great_sword\great sword crouching (2).glb"      "DongZhuo" "crouch"
Copy-Anim "great_sword\great sword jump (2).glb"           "DongZhuo" "jump"
Copy-Anim "great_sword\two handed sword death (2).glb"     "DongZhuo" "ko"
Copy-Anim "great_sword\great sword power up.glb"           "DongZhuo" "taunt"
Copy-Anim "great_sword\draw a great sword 2.glb"           "DongZhuo" "intro"
Copy-Anim "great_sword\great sword strafe (2).glb"         "DongZhuo" "dodge"
Copy-Anim "great_sword\great sword impact (3).glb"         "DongZhuo" "knockdown"

# ===== Guo Jia (Model006) — Tactician: magic caster + staff =====
Write-Host "`n--- GuoJia (tactician magic) ---"
Copy-Anim "magic_caster\standing idle.glb"                       "GuoJia" "idle"
Copy-Anim "magic_caster\Standing Walk Forward.glb"               "GuoJia" "walk_fwd"
Copy-Anim "magic_caster\Standing Walk Back.glb"                  "GuoJia" "walk_back"
Copy-Anim "magic_caster\Standing Run Forward.glb"                "GuoJia" "run_fwd"
Copy-Anim "magic_caster\Standing Run Back.glb"                   "GuoJia" "run_back"
Copy-Anim "magic_caster\Standing 1H Magic Attack 01.glb"         "GuoJia" "attack_6"
Copy-Anim "magic_caster\Standing 2H Magic Area Attack 02.glb"    "GuoJia" "attack_10"
Copy-Anim "magic_caster\Standing React Small From Front.glb"     "GuoJia" "hit_react"
Copy-Anim "magic_caster\Standing React Large From Front.glb"     "GuoJia" "knockdown"
Copy-Anim "magic_caster\Standing React Death Backward.glb"       "GuoJia" "ko"
Copy-Anim "magic_caster\Standing Jump.glb"                       "GuoJia" "jump"

# ===== Huang Gai (Model007) — Vanguard: unarmed brawler with great sword kicks =====
Write-Host "`n--- HuangGai (unarmed brawler + kicks) ---"
Copy-Anim "great_sword\great sword kick.glb"               "HuangGai" "attack_4"
Copy-Anim "great_sword\great sword kick (2).glb"           "HuangGai" "attack_5"
Copy-Anim "great_sword\great sword slide attack.glb"       "HuangGai" "attack_7"
Copy-Anim "great_sword\great sword jump attack.glb"        "HuangGai" "attack_10"
Copy-Anim "great_sword\great sword impact.glb"             "HuangGai" "hit_react"
Copy-Anim "great_sword\great sword impact (3).glb"         "HuangGai" "knockdown"
Copy-Anim "great_sword\great sword idle (3).glb"           "HuangGai" "idle"
Copy-Anim "great_sword\great sword blocking.glb"           "HuangGai" "block"
Copy-Anim "great_sword\great sword power up.glb"           "HuangGai" "taunt"
Copy-Anim "great_sword\great sword crouching (3).glb"      "HuangGai" "crouch"

# ===== Huang Yueying (Model008) — Inventor: longbow locomotion + ranged =====
Write-Host "`n--- HuangYueying (inventor ranged) ---"
Copy-Anim "longbow\standing idle 01.glb"                   "HuangYueying" "idle"
Copy-Anim "longbow\standing walk forward.glb"              "HuangYueying" "walk_fwd"
Copy-Anim "longbow\standing walk back.glb"                 "HuangYueying" "walk_back"
Copy-Anim "longbow\standing run forward.glb"               "HuangYueying" "run_fwd"
Copy-Anim "longbow\standing run back.glb"                  "HuangYueying" "run_back"
Copy-Anim "magic_caster\Standing React Small From Front.glb" "HuangYueying" "hit_react"
Copy-Anim "magic_caster\Standing React Death Backward.glb"   "HuangYueying" "ko"
Copy-Anim "magic_caster\Standing 1H Magic Attack 01.glb"     "HuangYueying" "attack_9"

# ===== Xu Kui (Model009) — Shadow Blade: fast sword+shield assassin =====
Write-Host "`n--- XuKui (shadow blade assassin) ---"
Copy-Anim "sword_shield\sword and shield attack (4).glb"    "XuKui" "attack_1"
Copy-Anim "sword_shield\sword and shield attack (3).glb"    "XuKui" "attack_2"
Copy-Anim "sword_shield\sword and shield slash (4).glb"     "XuKui" "attack_4"
Copy-Anim "sword_shield\sword and shield slash (5).glb"     "XuKui" "attack_5"
Copy-Anim "sword_shield\sword and shield kick.glb"          "XuKui" "attack_7"
Copy-Anim "sword_shield\sword and shield impact.glb"        "XuKui" "hit_react"
Copy-Anim "sword_shield\sword and shield impact (3).glb"    "XuKui" "block_stun"
Copy-Anim "sword_shield\sword and shield idle (2).glb"      "XuKui" "idle"
Copy-Anim "sword_shield\sword and shield block.glb"         "XuKui" "block"
Copy-Anim "sword_shield\sword and shield block (2).glb"     "XuKui" "parry"
Copy-Anim "sword_shield\sword and shield death (2).glb"     "XuKui" "ko"
Copy-Anim "sword_shield\sword and shield run (2).glb"       "XuKui" "run_fwd"
Copy-Anim "sword_shield\sword and shield walk (2).glb"      "XuKui" "walk_fwd"
Copy-Anim "sword_shield\sword and shield strafe (3).glb"    "XuKui" "dodge"
Copy-Anim "sword_shield\sword and shield crouch idle.glb"   "XuKui" "crouch"

# ===== Liu Bei (Model010) — Warlord: balanced dual sword =====
Write-Host "`n--- LiuBei (warlord balanced) ---"
Copy-Anim "sword_shield\sword and shield attack (2).glb"    "LiuBei" "attack_1"
Copy-Anim "sword_shield\sword and shield attack.glb"        "LiuBei" "attack_2"
Copy-Anim "sword_shield\sword and shield slash (2).glb"     "LiuBei" "attack_4"
Copy-Anim "sword_shield\sword and shield slash (3).glb"     "LiuBei" "attack_5"
Copy-Anim "sword_shield\sword and shield slash.glb"         "LiuBei" "attack_6"
Copy-Anim "sword_shield\sword and shield casting.glb"       "LiuBei" "attack_9"
Copy-Anim "sword_shield\sword and shield impact (2).glb"    "LiuBei" "hit_react"
Copy-Anim "sword_shield\sword and shield idle (3).glb"      "LiuBei" "idle"
Copy-Anim "sword_shield\sword and shield block.glb"         "LiuBei" "block"
Copy-Anim "sword_shield\sword and shield death.glb"         "LiuBei" "ko"
Copy-Anim "sword_shield\sword and shield run.glb"           "LiuBei" "run_fwd"
Copy-Anim "sword_shield\sword and shield walk.glb"          "LiuBei" "walk_fwd"
Copy-Anim "sword_shield\sword and shield power up.glb"      "LiuBei" "taunt"
Copy-Anim "sword_shield\sword and shield strafe (4).glb"    "LiuBei" "dodge"

# ===== Lu Bu (Model011) — God of War: great sword power + magic specials =====
Write-Host "`n--- LuBu (god of war power) ---"
Copy-Anim "great_sword\great sword slash (2).glb"          "LuBu" "attack_1"
Copy-Anim "great_sword\great sword slash (5).glb"          "LuBu" "attack_2"
Copy-Anim "great_sword\great sword high spin attack.glb"   "LuBu" "attack_4"
Copy-Anim "great_sword\great sword kick.glb"               "LuBu" "attack_5"
Copy-Anim "great_sword\great sword kick (2).glb"           "LuBu" "attack_8"
Copy-Anim "great_sword\great sword casting.glb"            "LuBu" "attack_9"
Copy-Anim "great_sword\great sword slide attack.glb"       "LuBu" "attack_10"
Copy-Anim "great_sword\great sword blocking (2).glb"       "LuBu" "block"
Copy-Anim "great_sword\great sword blocking (3).glb"       "LuBu" "parry"
Copy-Anim "great_sword\great sword impact (5).glb"         "LuBu" "hit_react"
Copy-Anim "great_sword\great sword impact (4).glb"         "LuBu" "knockdown"
Copy-Anim "great_sword\great sword idle (4).glb"           "LuBu" "idle"
Copy-Anim "great_sword\great sword run (2).glb"            "LuBu" "run_fwd"
Copy-Anim "great_sword\great sword walk (2).glb"           "LuBu" "walk_fwd"
Copy-Anim "great_sword\great sword crouching (4).glb"      "LuBu" "crouch"
Copy-Anim "great_sword\great sword jump (2).glb"           "LuBu" "jump"
Copy-Anim "great_sword\two handed sword death.glb"         "LuBu" "ko"
Copy-Anim "great_sword\great sword power up.glb"           "LuBu" "taunt"
Copy-Anim "great_sword\draw a great sword 1.glb"           "LuBu" "intro"
Copy-Anim "great_sword\great sword strafe (3).glb"         "LuBu" "dodge"

# ===== Lu Meng (Model012) — Blade Master: precise sword+shield, different from CaoPi =====
Write-Host "`n--- LuMeng (blade master precise) ---"
Copy-Anim "sword_shield\sword and shield slash.glb"         "LuMeng" "attack_1"
Copy-Anim "sword_shield\sword and shield slash (2).glb"     "LuMeng" "attack_2"
Copy-Anim "sword_shield\sword and shield slash (3).glb"     "LuMeng" "attack_3"
Copy-Anim "sword_shield\sword and shield attack (4).glb"    "LuMeng" "attack_4"
Copy-Anim "sword_shield\sword and shield attack (3).glb"    "LuMeng" "attack_5"
Copy-Anim "sword_shield\sword and shield attack (2).glb"    "LuMeng" "attack_6"
Copy-Anim "sword_shield\sword and shield kick.glb"          "LuMeng" "attack_7"
Copy-Anim "sword_shield\sword and shield slash (5).glb"     "LuMeng" "attack_8"
Copy-Anim "sword_shield\sword and shield casting (2).glb"   "LuMeng" "attack_9"
Copy-Anim "sword_shield\sword and shield slash (4).glb"     "LuMeng" "attack_10"
Copy-Anim "sword_shield\sword and shield block (2).glb"     "LuMeng" "block"
Copy-Anim "sword_shield\sword and shield block.glb"         "LuMeng" "parry"
Copy-Anim "sword_shield\sword and shield impact (3).glb"    "LuMeng" "hit_react"
Copy-Anim "sword_shield\sword and shield impact (2).glb"    "LuMeng" "block_stun"
Copy-Anim "sword_shield\sword and shield idle (4).glb"      "LuMeng" "idle"
Copy-Anim "sword_shield\sword and shield run (2).glb"       "LuMeng" "run_fwd"
Copy-Anim "sword_shield\sword and shield walk (2).glb"      "LuMeng" "walk_fwd"
Copy-Anim "sword_shield\sword and shield crouching.glb"     "LuMeng" "crouch"
Copy-Anim "sword_shield\sword and shield jump (2).glb"      "LuMeng" "jump"
Copy-Anim "sword_shield\sword and shield death (2).glb"     "LuMeng" "ko"
Copy-Anim "sword_shield\sheath sword 2.glb"                 "LuMeng" "intro"
Copy-Anim "sword_shield\sword and shield strafe (2).glb"    "LuMeng" "dodge"
Copy-Anim "sword_shield\sword and shield power up.glb"      "LuMeng" "victory"

Write-Host "`nDone! Per-character animation folders created."
